#!/bin/bash

build() {
        add_all_modules -f 'nls' '/kernel/fs'
        add_all_modules -f 'overlayfs' '/kernel/fs'
        add_all_modules -f 'squashs' '/kernel/fs'
        add_all_modules -f 'udf' '/kernel/fs'
        add_all_modules -f 'ext4' '/kernel/fs'
}

help() {
    cat <<HELPEOF
This hook adds filesystems modules to the image. If you would like to minimize
the modules installed in the image, add the autodetect hook too.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
